### ISSUE TITLE
Xcode Building Errors

### ISSUE THREAD

**Issue by rileyprev** [kivy/kivy-ios#534] opened 2020-07-24 17:29 UTC
Hello, I've been trying to build my first app on Xcode and I've come across these errors:

/Users/rileyprevost/app-one-ios/YourApp/venv/lib/python3.7/site-packages/kivy/extras/highlight.py:45: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if len(sys.argv) is not 4:
/Users/rileyprevost/app-one-ios/YourApp/venv/lib/python3.7/site-packages/kivy/uix/behaviors/focus.py:463: SyntaxWarning: "is" with a literal. Did you mean "=="?
  walk_tree = 'walk' if focus_dir is 'focus_next' else 'walk_reverse'
/Users/rileyprevost/app-one-ios/YourApp/venv/lib/python3.7/site-packages/kivy/uix/behaviors/focus.py:476: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if focus_dir is 'focus_next':
/Users/rileyprevost/app-one-ios/YourApp/venv/lib/python3.7/site-packages/kivy/uix/behaviors/knspace.py:460: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if parent_knspace is not 0:
/Users/rileyprevost/app-one-ios/YourApp/venv/lib/python3.7/site-packages/kivymd/uix/picker.py:625: SyntaxWarning: "is" with a literal. Did you mean "=="?
  op = 1 if operation is "next" else -1
/Users/rileyprevost/app-one-ios/YourApp/venv/lib/python3.7/site-packages/mpmath/ctx_mp_python.py:892: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if other is 0:
/Users/rileyprevost/app-one-ios/YourApp/venv/lib/python3.7/site-packages/mpmath/ctx_mp_python.py:986: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if other is 0:
/Users/rileyprevost/app-one-ios/YourApp/venv/lib/python3.7/site-packages/pandas/tests/frame/test_alter_axes.py:241: SyntaxWarning: "is" with a literal. Did you mean "=="?
  False if (keys[0] is "A" and keys[1] is "A") else drop  # noqa: F632
/Users/rileyprevost/app-one-ios/YourApp/venv/lib/python3.7/site-packages/pandas/tests/frame/test_alter_axes.py:241: SyntaxWarning: "is" with a literal. Did you mean "=="?
  False if (keys[0] is "A" and keys[1] is "A") else drop  # noqa: F632
/Users/rileyprevost/app-one-ios/YourApp/venv/lib/python3.7/site-packages/traitlets/config/loader.py:795: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if len(key) is 1:
/Users/rileyprevost/app-one-ios/YourApp/venv/lib/python3.7/site-packages/traitlets/config/loader.py:804: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if len(key) is 1:
Command PhaseScriptExecution failed with a nonzero exit code

I've tried to redo the process of building a new Xcode project through the command line multiple times to no avail. Any help or explanation would be greatly appreciated. Thank you.

**Comment by liu00222** [comment] 2020-07-26 05:17
I am suffering from the same error... Hope someone can help solve this problem. Thanks

**Comment by rileyprev** [comment] 2020-07-28 15:33
I got these errors when I tried to run my XCode project after creating it from the command line. I am running it from a venv.

**Comment by Zen-CODE** [comment] 2020-07-28 19:34
Ah. It looks like your `venv` folder in inside of you app folder. So when it copies your app code into the XCode project, it's also copying in the `venv` files. The `venv` folder should not be in the <app_folder> you point to with:

    python3 toolchain.py create <app_name> <app_folder>

Please move it  out of there and try again?

**Comment by rileyprev** [comment] 2020-07-28 22:47
Thank you that worked. However, I'm getting another error when I try to run my app through the iPhone Simulator:

2020-07-28 18:43:44.262074-0400 calcapp[12235:1274114] Available orientation: KIVY_ORIENTATION=LandscapeLeft LandscapeRight Portrait PortraitUpsideDown
2020-07-28 18:43:44.262281-0400 calcapp[12235:1274114] Initializing python
2020-07-28 18:43:44.459239-0400 calcapp[12235:1274114] Running main.py: /Users/rileyprevost/Library/Developer/CoreSimulator/Devices/48F0FB90-26BC-4A79-9F28-3749CD1D22B5/data/Containers/Bundle/Application/91973492-D222-4DA7-8C19-4715F7CBDE94/calcapp.app/YourApp/main.pyc
[INFO   ] [Kivy        ] v2.0.0rc1, git-Unknown, 20200728
[INFO   ] [Kivy        ] Installed at "/Users/rileyprevost/Library/Developer/CoreSimulator/Devices/48F0FB90-26BC-4A79-9F28-3749CD1D22B5/data/Containers/Bundle/Application/91973492-D222-4DA7-8C19-4715F7CBDE94/calcapp.app/lib/python3.8/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.8.2 (default, Jul 28 2020, 18:16:36) 
[Clang 11.0.3 (clang-1103.0.32.62)]
[INFO   ] [Python      ] Interpreter at "/Users/rileyprevost/Library/Developer/CoreSimulator/Devices/48F0FB90-26BC-4A79-9F28-3749CD1D22B5/data/Containers/Bundle/Application/91973492-D222-4DA7-8C19-4715F7CBDE94/calcapp.app/calcapp"
 Traceback (most recent call last):
   File "/Users/rileyprevost/Desktop/CalcApp/calcapp-ios/YourApp/main.py", line 6, in <module>
 ModuleNotFoundError: No module named 'kivymd'
2020-07-28 18:43:44.623113-0400 calcapp[12235:1274114] Application quit abnormally!
2020-07-28 18:43:44.636107-0400 calcapp[12235:1274114] Leaving

**Comment by Zen-CODE** [comment] 2020-07-29 05:14
Okaty, then you probably need to install kivymd?

    python toolchain.py pip install kivymd

**Comment by rileyprev** [comment] 2020-07-29 16:46
I already have all of the necessary modules installed into the venv, but it still gives me the "ModuleNotFoundError: No module named 'kivymd'."

**Comment by Zen-CODE** [comment] 2020-07-29 17:22
Yes, the `venv` is not what gets deployed to iOS. It's needs to be added to the `hostpython` instance: the python interpreter that does ges deployed to iOS. The above command should do that. Try it?

**Comment by rileyprev** [comment] 2020-07-29 18:23
I got this error when I entered that command:

Traceback (most recent call last):
  File "toolchain.py", line 14, in <module>
    import sh
ImportError: No module named sh

**Comment by Zen-CODE** [comment] 2020-07-30 05:47
That means you have not installed the requirement in your `vevn` or are not running that command in you `venv`. Activate you `venv`, install the requirements and try again.

**Comment by rileyprev** [comment] 2020-08-02 14:39
I get an error when I try to install kivymd:

(venv) rileyprevost@Rileys-MBP kivy_ios % python toolchain.py pip install kivymd
toolchain.py:96: DeprecationWarning: ChromeDownloader style of invoking requests is deprecated. Use newer urlopen functions/methods
  urlretrieve = ChromeDownloader().retrieve
[ERROR   ] python must be compiled before using pip

**Comment by Zen-CODE** [comment] 2020-08-03 06:01
? The same command works for me. And the message makes does not make sense.  Have you run:

    python toolchain.py build kivy python3 openssl

already? If so, try 

    python toolchain.py build hostpython3

and try again?

**Comment by Zen-CODE** [comment] 2020-08-11 15:18
Okay, I'm going to close this issue as the original error was clearly caused by including the `venv` folder in the source folder for the XCode application. The subsequent errors are different, but probably also caused by incorrect setup.

@rileyprev If you continue to experience issues, you can continue to post here or ask on the forums, but the original issue this ticket was created for is invalid.

Thanks.

**Closed by Zen-CODE** 2020-08-11 15:18 UTC
Labels: awaiting-reply
