### ISSUE TITLE
When starting with device in landscape, window height/width are swapped 

### ISSUE THREAD

**Issue by hackalog** [kivy/kivy-ios#321] opened 2018-12-11 15:23 UTC
Create any kivy app intended to run in landscape mode, and run it in the XCode iPhone simulator (I use the iphone 8plus target) set to Landscape orientation (or auto), and the following in your `main.m`:
```
void export_orientation() {
    // 1. Landscape only
    NSString *result = [[NSString alloc] initWithString:@"KIVY_ORIENTATION=LandscapeLeft LandscapeRight"];

    putenv((char *)[result UTF8String]);
    NSLog(@"Available orientation: %@", result);
}
```

On first run, the screen size will be wrong. Pressing home and re-entering the app lays out the screen correctly.

e.g. (This app does nothing, but you should see the screen size is very, very wrong on first run)

```
import kivy
from kivy.app import App
from kivy.lang import Builder

kv = Builder.load_string('''
BoxLayout:
    orientation: 'vertical'
    Label:
        text: 'label'
    AnchorLayout:
        Button:
            size_hint: .5, .5
            text: 'Press Me'
''')

class DemoApp(App):

    def build(self):
        self.root = kv
        return self.root

if __name__ == '__main__':
    DemoApp().run()
```

**Comment by hackalog** [comment] 2018-12-11 15:34
(I have no idea if the above is the "recommended" way to make an IOS app landscape-only. This code has been in our tree for a few years now, but it leads to an easy reproducer for some rotation-related issues)

**Comment by Zen-CODE** [comment] 2020-06-29 19:24
Cannot reproduce this? Running the above code in landscape mode gives me exactly what I expect See below? 

[
![Screenshot 2020-06-29 at 21 23 21](https://user-images.githubusercontent.com/3539755/86047201-d4e1ba80-ba4e-11ea-8bb7-955319f34616.png)
](url)

**Comment by Zen-CODE** [comment] 2020-07-10 07:59
Given this is quite old and we cannot reproduce it, I'm going to close this. Please feel free to re-open with fresh information. Thanks

**Closed by Zen-CODE** 2020-07-10 07:59 UTC
