### ISSUE TITLE
Kivy image not showing after compiling with toolchain

### ISSUE THREAD

**Issue by RustyRyan98** [kivy/kivy-ios#517] opened 2020-06-12 16:21 UTC
I deployed the home page of my app just to see how it would look on an ios device an image which is showing on my python code is not showing in Xcode. Please i would appreciate assistance. Thank you

**Comment by Zen-CODE** [comment] 2020-06-26 02:27
For assistance, please post here: https://groups.google.com/forum/#!forum/kivy-users

If you want to report an issue, we would require concrete evidence that the problem is indeed a kivy-ios problem. "Showing in python code" does not make sense? Python is just code and does not display anything unless run within a context? Please post the steps you followed, and elaborate on exactly where and what the problem is?

Thanks

**Comment by Zen-CODE** [comment] 2020-07-10 08:19
Closing now. Please re-open with a code example if you are still experiencing this issue.

Thanks

**Closed by Zen-CODE** 2020-07-10 08:19 UTC
Labels: awaiting-reply
