### ISSUE TITLE
Cache execution error? Download is ignored when it is not complete(a corrupt download)

### ISSUE THREAD

**Issue by andong777** [kivy/kivy-ios#179] opened 2016-03-17 16:09 UTC
I run the command `./toolchain.py build kivy` and it tells me that a corrupt download occurs.

> This is usually caused by a corrupt download. The file will be removed and re-downloaded on the next run.

I follow the instruction and run it again. And this time it says the download is ignored, with no file downloaded successfully, and errors occur accordingly. 

> (ignored) Download

I skim the code and find the following code:

```
if key in state and not force:
    print("# (ignored) {} {}".format(f.__name__.capitalize(), self.name))
    return
```

It seems the key should have been deleted from state but it does not. 
As for the force option, it is not well documented and I don't know how to 'force' the download.

By the way, I at last finish the download by the command 'distclean'. :)
##

**Comment by Zen-CODE** [comment] 2016-04-12 20:28
Is that all that gets displayed? The code around this issue is as follows:

                print('Error extracting the archive {0}'.format(filename))
                print('This is usually caused by a corrupt download. The file'
                      ' will be removed and re-downloaded on the next run.')
                remove(filename)

So, you should not only get a printout of the filename, but if it can't be deleted, you should get an error message? Do you get any of these?

Thanks

**Comment by andong777** [comment] 2016-04-13 04:16
@Zen-CODE Reproducing the situation is not very difficult. 
In the first attachment, I tried to build kivy, and it failed to download freetype, and as before, it says the file will be re-downloaded in the next run. Then in the second attachment, I tried to build freetype, the bug ("# (ignored) Download freetype") was reproduced.
I don't get any output about deleting the file.
Besides, when I tried to reproduce the bug, I turned off the internet during the download. Then in the next run, the download was still ignored, but the output looks different. See it in the third attachment.

[1.txt](https://github.com/kivy/kivy-ios/files/216372/1.txt)
[2.txt](https://github.com/kivy/kivy-ios/files/216373/2.txt)
[3.txt](https://github.com/kivy/kivy-ios/files/216374/3.txt)

**Comment by Zen-CODE** [comment] 2016-04-13 20:26
Yes, odd. Your third build log does not even mention freetype. In my experience, the

    AttributeError: 'NoneType' object has no attribute 'startswith'

error is always always a download issue. We work behind a restrictive firewall, so I've had this a few times. I see in the last build, you're using numpy, which can be complicated as it needs a recipes/os dependent binaries AFAIK. Could you try running a vanilla plain-jane hello world kivy app to just to establish whether the core Kivy framework works? Is so, we know freetype is running, which just leaves the numpy issues.

Of course, we still need to try and make the message clearer and the fail more elegant, but at least that info would help to establish what is happening.

**Comment by andong777** [comment] 2016-04-14 05:24
@Zen-CODE Yes, I can build kivy successfully after a few tries (depending on the internet connectivity), and run kivy apps on my iOS device, as I said in the first comment.
But I think it IS a bug to not re-download the file, as it tells me it will re-download the file on the next run.

As for the third attachment, I think it has nothing to do with numpy. I built numpy before, and there is nothing wrong. 
It is because I manually turned off the internet connection during the download, trying to reproduce the situation, and on the next run, it outputted that.
The output is different in the third attachment. I think it is another bug of download, so I add it as an attachment.

**Comment by Zen-CODE** [comment] 2016-04-14 16:03
Yes, we've really got to try and make this consistent. I just can't see from the code what is happening. I added that try/except for the corrupt download but I can't see how this situation would occur?

It should delete the cached file and then start from scratch the next time. The fact that it eventually works is an improvement, but clearly there is something I am not understanding. Let me do some more robust testing and get back to you....

**Comment by andong777** [comment] 2016-04-14 16:17
ok, thank you. Ask me if you want any information.

**Comment by Zen-CODE** [comment] 2016-11-25 12:38
Thanks, I've merged a fix for this. Works for me, but it's tricky to reproduce, If you could test it, I would be grateful (just pull the latest).

If it still occurs, please post here and I'll look into it.

**Closed by Zen-CODE** 2016-11-25 12:38 UTC
