### ISSUE TITLE
Issue adding Pillow to Kivy-ios build

### ISSUE THREAD

**Issue by Neutron-Jimmy** [kivy/kivy-ios#807] opened 2023-05-18 16:06 UTC
* Python : 3.10.11
* MacOS version : 13.3.1
* XCode Version : 14.3
* Cython version : 0.29.28

**Describe the bug**
When creating a toolchain build including the recipe for Pillow, I receive the following error in Xcode: "407 duplicate symbols for architecture arm64"

**To Reproduce**
In a python environment run the following commands: 

toolchain build python3 kivy pillow

or 

toolchain build python3 kivy
toolchain build pillow

Both methods produces the same error

**Expected behavior**
The rest of my project works perfectly fine without Pillow, and I have the app working as intended on Android without any issues. I need Pillow for the loading and displaying of images in the app.

**Additional context**
I tried installing pillow with "toolchain pip install pillow" but that leads to a different issue.

**Comment by Cheaterman** [comment] 2023-05-18 16:15
Duplicate of #787, try [this workaround](https://github.com/kivy/kivy-ios/issues/787#issuecomment-1489027427).

**Closed** 2023-05-18 16:21 UTC
