### ISSUE TITLE
Build kivy-ios failed with xcode 7.1.1

### ISSUE THREAD

**Issue by sunsolve** [kivy/kivy-ios#166] opened 2015-11-23 11:11 UTC
I checked out latest ios-kivy and build,but it failed when building hostpython, using xcode 7.1.1 on XI Captian

```
$ ./toolchain.py recipes
audiostream  master
ffmpeg       2.6.3
ffpyplayer   master
freetype     2.5.5
host_setuptools None
hostlibffi   3.2.1
hostpython   2.7.1
ios          master
kivy         1.9.0
libffi       3.2.1
libjpeg      v9a
moodstocks   4.1.5
numpy        1.9.1
openssl      1.0.2d
photolibrary master
pil          2.8.2
pkgresources None
plyer        master
pycrypto     2.6.1
pymoodstocks master
pyobjus      master
python       2.7.1
sdl2         iOS-improvements
sdl2_image   2.0.0
sdl2_mixer   2.0.0
sdl2_ttf     2.0.12
```
```
$ ./toolchain.py build kivy
x Python-2.7.1/Mac/Modules/carbonevt/CarbonEvtscan.py
x Python-2.7.1/Mac/Modules/carbonevt/_CarbonEvtmodule.c
x Python-2.7.1/Mac/Modules/ColorPickermodule.c
x Python-2.7.1/Mac/Modules/icgluemodule.c
x Python-2.7.1/Mac/Modules/_scproxy.c
x Python-2.7.1/Mac/Modules/ae/
x Python-2.7.1/Mac/Modules/ae/_AEmodule.c
x Python-2.7.1/Mac/Modules/ae/README
x Python-2.7.1/Mac/Modules/ae/aescan.py
x Python-2.7.1/Mac/Modules/ae/aesupport.py
x Python-2.7.1/Mac/Demo/
x Python-2.7.1/Mac/Demo/example2/
x Python-2.7.1/Mac/Demo/example2/dnslookup-2.rsrc
x Python-2.7.1/Mac/Demo/example2/dnslookup-2.gif
x Python-2.7.1/Mac/Demo/example2/dnslookup-2.py
x Python-2.7.1/Mac/Demo/mlte/
x Python-2.7.1/Mac/Demo/mlte/mlted.py
x Python-2.7.1/Mac/Demo/example1.html
x Python-2.7.1/Mac/Demo/quicktime/
x Python-2.7.1/Mac/Demo/quicktime/MovieInWindow.py
x Python-2.7.1/Mac/Demo/quicktime/VerySimplePlayer.py
x Python-2.7.1/Mac/Demo/PICTbrowse/
x Python-2.7.1/Mac/Demo/PICTbrowse/oldPICTbrowse.py
x Python-2.7.1/Mac/Demo/PICTbrowse/oldPICTbrowse.rsrc
x Python-2.7.1/Mac/Demo/PICTbrowse/ICONbrowse.py
x Python-2.7.1/Mac/Demo/PICTbrowse/PICTbrowse.rsrc
x Python-2.7.1/Mac/Demo/PICTbrowse/PICTbrowse.py
x Python-2.7.1/Mac/Demo/PICTbrowse/PICTbrowse2.py
x Python-2.7.1/Mac/Demo/PICTbrowse/cicnbrowse.py
x Python-2.7.1/Mac/Demo/textedit/
x Python-2.7.1/Mac/Demo/textedit/ped.py
x Python-2.7.1/Mac/Demo/resources/
x Python-2.7.1/Mac/Demo/resources/listres.py
x Python-2.7.1/Mac/Demo/resources/copyres.py
x Python-2.7.1/Mac/Demo/html.icons/
x Python-2.7.1/Mac/Demo/html.icons/createmake.png
x Python-2.7.1/Mac/Demo/html.icons/options.gif
x Python-2.7.1/Mac/Demo/html.icons/mkapplet.gif
x Python-2.7.1/Mac/Demo/html.icons/python.gif
x Python-2.7.1/Mac/Demo/html.icons/preferences.gif
x Python-2.7.1/Mac/Demo/example0/
x Python-2.7.1/Mac/Demo/example0/checktext.py
x Python-2.7.1/Mac/Demo/index.html
x Python-2.7.1/Mac/Demo/example2.html
x Python-2.7.1/Mac/Demo/textedit.html
x Python-2.7.1/Mac/Demo/imgbrowse/
x Python-2.7.1/Mac/Demo/imgbrowse/imgbrowse.py
x Python-2.7.1/Mac/Demo/imgbrowse/mac_image.py
x Python-2.7.1/Mac/Demo/applescript/
x Python-2.7.1/Mac/Demo/applescript/Disk_Copy/
x Python-2.7.1/Mac/Demo/applescript/Disk_Copy/Standard_Suite.py
x Python-2.7.1/Mac/Demo/applescript/Disk_Copy/__init__.py
x Python-2.7.1/Mac/Demo/applescript/Disk_Copy/Utility_Events.py
x Python-2.7.1/Mac/Demo/applescript/Disk_Copy/Special_Events.py
x Python-2.7.1/Mac/Demo/applescript/makedisk.py
x Python-2.7.1/Mac/Demo/example0.html
x Python-2.7.1/Mac/Demo/applescript.html
x Python-2.7.1/Mac/Demo/example1/
x Python-2.7.1/Mac/Demo/example1/dnslookup-1.gif
x Python-2.7.1/Mac/Demo/example1/dnslookup-1.rsrc
x Python-2.7.1/Mac/Demo/example1/dnslookup-1.py
x Python-2.7.1/Mac/Demo/sound/
x Python-2.7.1/Mac/Demo/sound/morselib.py
x Python-2.7.1/Mac/Demo/sound/playaiff.py
x Python-2.7.1/Mac/Demo/sound/morse.py
Build_all hostpython
Build hostpython for x86_64 (filtered)
Build hostpython
Prebuild hostpython for x86_64
Copy _scproxy.py to Lib/_scproxy.py
Apply patch ssize-t-max.patch
Apply patch dynload.patch
Apply patch static-_sqlite3.patch
Copy ModulesSetup to Modules/Setup.local
Build hostpython for x86_64
checking for --enable-universalsdk... no
checking for --with-universal-archs... 32-bit
..............................
...........................
checking for tv_nsec2 in struct stat... yes
checking whether mvwdelch is an expression... yes
checking whether WINDOW has _flags... no
checking for is_term_resized... yes
checking for resize_term... yes
checking for resizeterm... yes
checking for /dev/ptmx... yes
checking for /dev/ptc... no
checking for %lld and %llu printf() format support... yes
checking for %zd printf() format support... yes
checking for socklen_t... yes
checking for build directories... done
configure: creating ./config.status
config.status: creating Makefile.pre
config.status: creating Modules/Setup.config
config.status: creating Misc/python.pc
config.status: creating Modules/ld_so_aix
config.status: creating pyc
creating Modules/Setup.local
creating Makefile
Makefile:1393: warning: overriding commands for target `Modules/posixmodule.o'
Makefile:1285: warning: ignoring old commands for target `Modules/posixmodule.o'
Makefile:1394: warning: overriding commands for target `Modules/posixmodule.so'
Makefile:1286: warning: ignoring old commands for target `Modules/posixmodule.so'
Makefile:1395: warning: overriding commands for target `Modules/errnomodule.o'
Makefile:1287: warning: ignoring old commands for target `Modules/errnomodule.o'
Makefile:1396: warning: overriding commands for target `Modules/errnomodule.so'
Makefile:1288: warning: ignoring old commands for target `Modules/errnomodule.so'
Makefile:1397: warning: overriding commands for target `Modules/pwdmodule.o'
Makefile:1289: warning: ignoring old commands for target `Modules/pwdmodule.o'
Makefile:1398: warning: overriding commands for target `Modules/pwdmodule.so'
Makefile:1290: warning: ignoring old commands for target `Modules/pwdmodule.so'
Makefile:1399: warning: overriding commands for target `Modules/_sre.o'
Makefile:1291: warning: ignoring old commands for target `Modules/_sre.o'
Makefile:1400: warning: overriding commands for target `Modules/_sre.so'
Makefile:1292: warning: ignoring old commands for target `Modules/_sre.so'
Makefile:1401: warning: overriding commands for target `Modules/_codecsmodule.o'
Makefile:1293: warning: ignoring old commands for target `Modules/_codecsmodule.o'
Makefile:1402: warning: overriding commands for target `Modules/_codecsmodule.so'
Makefile:1294: warning: ignoring old commands for target `Modules/_codecsmodule.so'
Makefile:1403: warning: overriding commands for target `Modules/_weakref.o'
Makefile:1311: warning: ignoring old commands for target `Modules/_weakref.o'
Makefile:1404: warning: overriding commands for target `Modules/_weakref.so'
Makefile:1312: warning: ignoring old commands for target `Modules/_weakref.so'
Makefile:1405: warning: overriding commands for target `Modules/zipimport.o'
Makefile:1295: warning: ignoring old commands for target `Modules/zipimport.o'
Makefile:1406: warning: overriding commands for target `Modules/zipimport.so'
Makefile:1296: warning: ignoring old commands for target `Modules/zipimport.so'
Makefile:1407: warning: overriding commands for target `Modules/symtablemodule.o'
Makefile:1297: warning: ignoring old commands for target `Modules/symtablemodule.o'
Makefile:1408: warning: overriding commands for target `Modules/_symtablemodule.so'
Makefile:1298: warning: ignoring old commands for target `Modules/_symtablemodule.so'
Makefile:1409: warning: overriding commands for target `Modules/xxsubtype.o'
Makefile:1354: warning: ignoring old commands for target `Modules/xxsubtype.o'
Makefile:1410: warning: overriding commands for target `Modules/xxsubtype.so'
Makefile:1355: warning: ignoring old commands for target `Modules/xxsubtype.so'
make: *** No rule to make target `python.exe'.  Stop.
Traceback (most recent call last):
  File "./toolchain.py", line 1225, in <module>
    ToolchainCL()
  File "./toolchain.py", line 1041, in __init__
    getattr(self, args.command)()
  File "./toolchain.py", line 1065, in build
    build_recipes(args.recipe, ctx)
  File "./toolchain.py", line 934, in build_recipes
    recipe.execute()
  File "/Volumes/data/zdata/temp/kivy/kivy-ios/toolchain.py", line 557, in execute
    self.build_all()
  File "/Volumes/data/zdata/temp/kivy/kivy-ios/toolchain.py", line 56, in _cache_execution
    f(self, *args, **kwargs)
  File "/Volumes/data/zdata/temp/kivy/kivy-ios/toolchain.py", line 644, in build_all
    self.build(arch)
  File "/Volumes/data/zdata/temp/kivy/kivy-ios/toolchain.py", line 56, in _cache_execution
    f(self, *args, **kwargs)
  File "/Volumes/data/zdata/temp/kivy/kivy-ios/toolchain.py", line 631, in build
    self.build_arch(arch)
  File "/Volumes/data/zdata/temp/kivy/kivy-ios/toolchain.py", line 679, in build_arch
    getattr(self, build)()
  File "/Volumes/data/zdata/temp/kivy/kivy-ios/recipes/hostpython/__init__.py", line 68, in build_x86_64
    _env=build_env)
  File "/Volumes/data/zdata/temp/kivy/kivy-ios/toolchain.py", line 39, in shprint
    for line in command(*args, **kwargs):
  File "./tools/external/sh.py", line 565, in next
    self.wait()
  File "./tools/external/sh.py", line 500, in wait
    self.handle_command_exit_code(exit_code)
  File "./tools/external/sh.py", line 516, in handle_command_exit_code
    raise exc(self.ran, self.process.stdout, self.process.stderr)
sh.ErrorReturnCode_2:

  RAN: '/usr/bin/make -C /Volumes/data/zdata/temp/kivy/kivy-ios/build/hostpython/x86_64/Python-2.7.1 -j4 python.exe Parser/pgen'

  STDOUT:
Makefile:1393: warning: overriding commands for target `Modules/posixmodule.o'
Makefile:1285: warning: ignoring old commands for target `Modules/posixmodule.o'
Makefile:1394: warning: overriding commands for target `Modules/posixmodule.so'
Makefile:1286: warning: ignoring old commands for target `Modules/posixmodule.so'
Makefile:1395: warning: overriding commands for target `Modules/errnomodule.o'
Makefile:1287: warning: ignoring old commands for target `Modules/errnomodule.o'
Makefile:1396: warning: overriding commands for target `Modules/errnomodule.so'
Makefile:1288: warning: ignoring old commands for target `Modules/errnomodule.so'
Makefile:1397: warning: overriding commands for target `Modules/pwdmodule.o'
Makefile:1289: warning: ignor... (2160 more, please see e.stdout)

  STDERR:
```

**Comment by satels** [comment] 2015-11-23 11:39
I fix this as:

Replace from "python.exe" to "python"

**Comment by sunsolve** [comment] 2015-11-23 13:15
@satels you are right,I changed it,and passed

**Comment by Zen-CODE** [comment] 2016-04-13 19:24
@sunsolve. So the issue is fixed? Please can you close it if this is the case. Otherwise, how can we change the docs to make it clearer?

**Comment by Zen-CODE** [comment] 2016-07-04 09:47
Thanks all. This issue has been fixed with this pr: https://github.com/kivy/kivy-ios/pull/182

**Closed by Zen-CODE** 2016-07-04 09:47 UTC
