### ISSUE TITLE
There is a memory leak in the program

### ISSUE THREAD

**Issue by zsf1975** [kivy/kivy-ios#419] opened 2020-01-29 01:52 UTC
Please forgive me for my English level. I found that xcode instruments reported multiple memory leaks in my program, and 48 memory leaks in the kivy touchtracer example, and no leaks after the program started 20 seconds later. I'm a kivy beginner, and I don't know if this is sdl2 2.0.9, python-specific garbage collection or other code problems. I'm concerned that this issue will affect the program's submission to the app store. I use kivy 2.0 rc, xcode 11, ios version 12-13.3.
In addition, each time the program starts, the program always outputs Unbalanced calls to begin/end appearance transitions SDL_uikitviewcontroller: 0x113de0cc.
Thanks for such a great program.
![screenshot 2020-01-29](https://user-images.githubusercontent.com/11973803/73321328-13dfca00-427d-11ea-94b4-46fd67a997d9.png)

**Comment by paulwilson90** [comment] 2021-10-10 11:47
Did you find a solution for the "Unbalanced calls" problem? I am currently getting the same thing happening to me.

**Comment by Julian-O** [comment] 2023-10-28 17:45
Closing as a support issue, not a bug. If this is in error, please let us know.

**Closed by Julian-O** 2023-10-28 17:45 UTC
