### ISSUE TITLE
[Request]: Pypi packages

### ISSUE THREAD

**Issue by jhay06** [kivy/kivy-ios#886] opened 2023-12-19 04:06 UTC
Make pypi packages of kivy-ios same with android counterpart , since kivy-ios pypi is very limited , so converting android kivy app to ios app will be a problem in terms of pypi packages thank you

**Comment by Julian-O** [comment] 2023-12-19 05:10
@jhay06:

Your request is unclear. 

There is a PyPI package for [Kivy for iOS](https://pypi.org/project/kivy-ios/).

There is a PyPI package for [python-for-android](https://pypi.org/project/python-for-android/).

What would your proposal look like if it was implemented?

**Comment by jhay06** [comment] 2023-12-19 06:16
hi @Julian-O  , thanks for the response . :) 

what i mean is , kivy-ios has a small list of available pypi packages vs to python-for-android , having limited with packages in kivy-ios will be a problem if for example i have android app and i would like to make it available also to ios but the package i used in android app is not available in kivy-ios then that would be a bigger problem . example tflite which is only available on android but not in ios , then the ios will end up using the native library then call it via pyobjus. 

hoping that pypi packages available in android will be available also on ios , to make it easier to dev to build kivy app.

Thank you very much . sorry for my bad english

**Comment by Julian-O** [comment] 2023-12-19 07:33
Ah, I think I understand. You are talking about *recipes*. You are pointing out that there are more python-for-android recipes than there are Kivy for iOS recipes.

Recipes take some effort to produce and to maintain. Generally recipes are only written when there is demand for them. They tend to be written by the volunteer developers who need them, and then made available to others.

So, if there is a particular recipe you need, please raise an issue. - or even better, write a recipe and contribute it back to be shared by others..

TensorFlow Lite (tflite) has already been requested for Kivy for iOS in #649. No-one has needed it enough to spend the effort to make a recipe and share it with others.

I am closing this as a duplicate of #649.

**Closed by Julian-O** 2023-12-19 07:33 UTC
Labels: feature request

**Comment by tcaduser** [comment] 2023-12-19 12:03
recipes for iOS are much more difficult than Android.  This is because an iOS recipe creates a static library with symbols that cannot have a name conflict with any other symbol in a Kivy iOS application.  If it is allowed by Apple, moving from static to dynamic frameworks would make recipe creation a much easier process.  However it is unclear if that is allowed, and Kivy iOS is only creating static libraries.

**Comment by jhay06** [comment] 2023-12-20 01:22
> Ah, I think I understand. You are talking about _recipes_. You are pointing out that there are more python-for-android recipes than there are Kivy for iOS recipes.
>  
YES

 
> TensorFlow Lite (tflite) has already been requested for Kivy for iOS in #649. No-one has needed it enough to spend the effort to make a recipe and share it with others.
> 
> I am closing this as a duplicate of #649.

No-one needed it based on ?, i believe there are some needs it . 

not only tensorflow , that is just an example . I just want to see in the future of kivy that devs from kivy-ios put priority or efforts to make pypi packages available from android to kivy-ios recipes also  to make it more cross platform without any additional task needed to when converting android app  to ios  . Just saying because not all devs knows how to make python recipe , like me i don't know how to really make python recipe , i tried but can't make it work  .

Any ways thank you very much .

**Comment by Julian-O** [comment] 2023-12-20 04:36
1) As tcaduser explained, just because someone wrote a recipe for python-for-android doesn't mean it is easy for a similar recipe to be written for Kivy for iOS.

2) The Kivy framework is based on the effort of volunteers. It isn't like a company where the CEO can say "Go and write recipes for these packages (even though no-one asked for them) because I think that will lead to new sales of Kivy." We have to wait for volunteers with the right skills to be motivated to do the work. There are already many suggestions for new recipes. 

3) I am **not** saying no-one needs tensorflow. I am saying no-one has needed it *enough* to spend the effort (or to sponsor someone to spend the effort). 

I, too, don't currently have the skills to write recipes. If I wanted a particular package, my choices would be: find an alternative (especially a pure Python one), learn how to write recipes, sponsor someone to do it, or raise an issue and wait (perhaps years) until someone else decided they needed it too.

**Comment by tcaduser** [comment] 2023-12-20 16:14
It looks like there are iOS build instructions here for TensorFlow Lite:
https://www.tensorflow.org/lite/guide/build_ios
I would think these instructions could be made part of a recipe.
