### ISSUE TITLE
 ModuleNotFoundError: No module named '_sqlite3'

### ISSUE THREAD

**Issue by d0kyuan** [kivy/kivy-ios#369] opened 2019-04-09 05:50 UTC
error like this :   
> File "/Users/rayyuan/Desktop/pack_server/static/kivy-ios/dottravel-ios/YourApp/src/py/mytool/mysqlite.py", line 2, in <module>
>    File "/var/containers/Bundle/Application/464C8611-CC8B-4491-B4F6-1C9F2F25FBA7/dottravel.app/lib/python37.zip/sqlite3/__init__.py", line 23, in <module>
>      Modules are automatically loaded from the Kivy path and User path:
>    File "/var/containers/Bundle/Application/464C8611-CC8B-4491-B4F6-1C9F2F25FBA7/dottravel.app/lib/python37.zip/sqlite3/dbapi2.py", line 27, in <module>
>  ModuleNotFoundError: No module named '_sqlite3'

i use 

> ./toolchain.py build python3 kivy

and i already include libsqlite3.tbd in Xcode10

**Comment by sgpy** [comment] 2019-06-08 05:04
Where you able to figure this one out? Found a similar [open](https://github.com/kivy/kivy-ios/issues/314) item

**Comment by tito** [comment] 2019-09-16 18:13
Yes, the sqlite3 python module is not compiled/missing. Duplicate of #314

**Closed by tito** 2019-09-16 18:13 UTC

**Comment by ccarro03** [comment] 2019-11-19 18:36
Hi - I have the same issue as d0kyuan. Is there a solution I can follow?

Thank you.
