### ISSUE TITLE
ImportError: No module named my_own_package

### ISSUE THREAD

**Issue by hoangvuche** [kivy/kivy-ios#334] opened 2019-01-11 12:19 UTC
Hi,

After running my kivy app in xcode, my app quits with ImportError as follows:

2019-01-11 19:09:38.095549+0700 billionaire[94769:420407] [framework] CUIThemeStore: No theme registered with id=0
2019-01-11 19:09:38.352457+0700 billionaire[94769:420407] Available orientation: KIVY_ORIENTATION=LandscapeLeft LandscapeRight Portrait PortraitUpsideDown
2019-01-11 19:09:38.352675+0700 billionaire[94769:420407] PythonHome is: /Users/vucheqh/Library/Developer/CoreSimulator/Devices/FDDACFC2-56A3-475C-BB3C-D2F7C2186469/data/Containers/Bundle/Application/FA96CC0C-FFCB-4228-80DF-4C76C4889B95/billionaire.app
2019-01-11 19:09:38.353210+0700 billionaire[94769:420407] Initializing python
2019-01-11 19:09:38.463939+0700 billionaire[94769:420407] Running main.py: /Users/vucheqh/Library/Developer/CoreSimulator/Devices/FDDACFC2-56A3-475C-BB3C-D2F7C2186469/data/Containers/Bundle/Application/FA96CC0C-FFCB-4228-80DF-4C76C4889B95/billionaire.app/YourApp/main.pyo
[INFO   ] [Kivy        ] v1.10.1
[INFO   ] [Python      ] v2.7.1 (r271:86832, Jan 10 2019, 23:28:31) 
[GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.5)]
 Traceback (most recent call last):
   File "/Users/vucheqh/kivy-ios/billionaire-ios/YourApp/main.py", line 13, in <module>
 ImportError: No module named common
2019-01-11 19:09:38.647709+0700 billionaire[94769:420407] Application quit abnormally!
2019-01-11 19:09:38.657427+0700 billionaire[94769:420407] Leaving

My common.py is existed at the same folder with main.py, I don't understand why it cannot import as expected. Please help me.
![screen shot 2019-01-11 at 7 16 02 pm](https://user-images.githubusercontent.com/24685745/51033307-909df880-15d5-11e9-851d-4d42f35bd363.png)

**Comment by hackalog** [comment] 2019-01-13 03:06
I am seeing this issue as well.

**Comment by hackalog** [comment] 2019-01-13 04:46
@hoangvuche try the workaround in #340 and let me know if that works for you.

**Comment by hoangvuche** [comment] 2019-01-13 04:51
Thanks @hackalog
I will check it out and let u know my result

**Comment by hoangvuche** [comment] 2019-01-13 16:13
@hackalog
It works after applying workaround #340 
Thanks so much.

**Comment by hackalog** [comment] 2019-01-14 22:07
Does this workaround work for you, @MDelaney7700 ?

**Comment by MDelaney7700** [comment] 2019-01-14 22:33
I've pulled changes, deleted and recreated the xcode project but the py files still seem to be getting deleted.

**Comment by hackalog** [comment] 2019-01-14 22:35
oh that's weird. and if you look in your project.pbxproj, you see the deletion lines commented out (as in: https://github.com/kivy/kivy-ios/pull/340/files)?

**Comment by hackalog** [comment] 2019-01-14 22:36
oh wait. (I just noticed the ifdef python 3.. sigh)

**Comment by MDelaney7700** [comment] 2019-01-15 18:48
If it is of any interest, I can confirm that it is a PYTHONPATH issue. I managed to get the imports to work by prepending 'YourApp' to my imports, so instead of being `from module import file`, it's now `from YourApp.module import file`

**Comment by hackalog** [comment] 2019-01-15 19:06
oh, that's interesting... thanks for the catch, @MDelaney7700

**Comment by hackalog** [comment] 2019-01-17 16:05
@MDelaney7700 can you retry again since the PYOPTIMIZE fix was merged? (https://github.com/kivy/kivy-ios/pull/340)

**Comment by ssolari** [comment] 2019-01-17 16:14
I don't know if its related, I did a pull and now my builds are breaking.   When I do a simple ```./toolchain.py create appttile ../path_to_mainpy``` the project does not pick up my module at all anymore.    It installs the default YourApp folder into my xcode project.      IF its different I can open a different issue.

**Comment by MDelaney7700** [comment] 2019-01-17 22:00
@hackalog I pulled changes, deleted and then rebuild python3, kivy and my project from scratch, but I'm afraid I'm having the same problem.

**Comment by mahomahomaho** [comment] 2019-02-06 20:38
In my case, such lines helped:

```
import sys
from os.path import dirname
sys.path.append(dirname(__file__))
```

**Comment by hackalog** [comment] 2019-02-06 20:48
Yeah, I glanced at the code path here: 
https://github.com/kivy/kivy-ios/blob/8f87410cf58e26d11194f1f8ca9571fa960633c6/tools/templates/%7B%7B%20cookiecutter.project_name%20%7D%7D-ios/main.m#L53-L65

I'm pretty sure @MDelaney7700 is right, and it just plain misses adding `YourApp` to the PYTHONPATH in the python3 code path. Perhaps setting the `PYTHONHOME` variable is not the same as setting `Py_SetPythonHome ` as is done in the python 2 case

**Comment by hackalog** [comment] 2019-02-06 20:51
Or perhaps setting PYTHONPATH explicitly overrides the default PYTHONHOME behavior

**Comment by Zen-CODE** [comment] 2020-06-26 03:35
Fixes merged as per: https://github.com/kivy/kivy-ios/pull/340. Please open a new issue if the problem persists.

**Closed by Zen-CODE** 2020-06-26 03:35 UTC
