### ISSUE TITLE
failed to build kivy-ios in OS X 10.11

### ISSUE THREAD

**Issue by wuyongyi** [kivy/kivy-ios#223] opened 2016-11-14 08:48 UTC
Just followed the document to git clone the latest  kivy-ios. however it was failed when

./toolchain.py build kivy (seems something wrong when the script tried to download freetype 2.5.5)

./toolchain.py build python was also failed when compiled.

**Comment by Zen-CODE** [comment] 2016-11-17 22:21
Please post the full log with the error in it. "Seems something went wrong" is a tad vague :-)

**Comment by wuyongyi** [comment] 2016-11-20 12:13
'./toolchain build kivy' failed when build host python, part of the log:

Undefined symbols for architecture x86_64:
  "_mkostemp", referenced from:
      _open_temp_exec_file_dir in libffi.a(closures.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [python.exe] Error 1
Traceback (most recent call last):
  File "./toolchain.py", line 1314, in <module>
    ToolchainCL()

**Comment by Zen-CODE** [comment] 2016-11-20 23:46
Okay, this seems to be a duplicate of this issue: https://github.com/kivy/kivy-ios/issues/211

Please follow up on that thread. Thanks :-)

**Closed by Zen-CODE** 2016-11-20 23:46 UTC
