### ISSUE TITLE
failed kivy-ios build 

### ISSUE THREAD

**Issue by xiushu53** [kivy/kivy-ios#267] opened 2017-10-05 14:46 UTC
I failed to build kivy-ios..

Mac OS Sierra 10.12.6
Xcode: 9.0
kivy-ios: 1.10.0
Cython: 0.25

I ran the build in the cond environment with python 2.7.
I referred to [https://github.com/kivy/kivy/wiki/Connecting-Kivy-with-Anaconda-(OSX)](https://github.com/kivy/kivy/wiki/Connecting-Kivy-with-Anaconda-(OSX))
and [https://kivy.org/docs/guide/packaging-ios.html](https://kivy.org/docs/guide/packaging-ios.html)

Especially, it seems that python build did not go well.

```
2 warnings and 1 error generated.
make: *** [Modules/posixmodule.o] Error 1
make: *** Waiting for unfinished jobs....
Traceback (most recent call last):
  File "./toolchain.py", line 1365, in <module>
    ToolchainCL()
  File "./toolchain.py", line 1114, in __init__
    getattr(self, args.command)()
  File "./toolchain.py", line 1155, in build
    build_recipes(args.recipe, ctx)
  File "./toolchain.py", line 1005, in build_recipes
    recipe.execute()
  File "/Users/mac/kivy-ios/toolchain.py", line 615, in execute
    self.build_all()
  File "/Users/mac/kivy-ios/toolchain.py", line 56, in _cache_execution
    f(self, *args, **kwargs)
  File "/Users/mac/kivy-ios/toolchain.py", line 704, in build_all
    self.build(arch)
  File "/Users/mac/kivy-ios/toolchain.py", line 56, in _cache_execution
    f(self, *args, **kwargs)
  File "/Users/mac/kivy-ios/toolchain.py", line 691, in build
    self.build_arch(arch)
  File "/Users/mac/kivy-ios/recipes/python/__init__.py", line 65, in build_arch
    "HOSTPGEN={}".format(self.ctx.hostpgen))
  File "/Users/mac/kivy-ios/toolchain.py", line 39, in shprint
    for line in command(*args, **kwargs):
  File "./tools/external/sh.py", line 565, in next
    self.wait()
  File "./tools/external/sh.py", line 500, in wait
    self.handle_command_exit_code(exit_code)
  File "./tools/external/sh.py", line 516, in handle_command_exit_code
    raise exc(self.ran, self.process.stdout, self.process.stderr)
sh.ErrorReturnCode_2: 

  RAN: '/usr/bin/make -j4 CROSS_COMPILE_TARGET=yes HOSTPYTHON=/Users/mac/kivy-ios/dist/hostpython/bin/python HOSTPGEN=/Users/mac/kivy-ios/dist/hostpython/bin/pgen'

  STDOUT:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -c -fno-strict-aliasing -arch i386 -pipe -no-cpp-precomp --sysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.0.sdk -O3 -miphoneos-version-min=6.0.0 -I/Users/mac/kivy-ios/dist/include/i386/freetype -I/Users/mac/kivy-ios/dist/include/i386/hostlibffi -I/Users/mac/kivy-ios/dist/include/i386/libffi -I/Users/mac/kivy-ios/dist/include/common/sdl2 -I/Users/mac/kivy-ios/dist/include/common/sdl2_image -I/Users/mac/kivy-ios/dist/include/common/sdl2_mixer -I/Users/mac/kivy-ios/dist/include/common/sdl2_ttf -DNDEBUG -g -fwrapv -O3 -W... (142967 more, please see e.stdout)

  STDERR:
```

Full output is [here](https://raw.githubusercontent.com/xiushu53/kivy_error/master/error_log).

**Comment by tonibagur** [comment] 2017-10-09 09:48
I had the same problem and I managed to fix it, I submited the following pull request:
https://github.com/kivy/kivy-ios/pull/268
I hope that this fix help you too.

**Comment by mbrockman1** [comment] 2017-10-09 17:49
This is still failing for me when trying to run '/toolchain.py build kivy'. Here is the total [output](https://gist.githubusercontent.com/mbrockman1/7cb7a11a71d5d73cf7b9e78e6b9d78b0/raw/1bd8147f6c774975532b44dbc1b7cdc1e7d63b5e/gistfile1.txt)

**Comment by xiushu53** [comment] 2017-10-11 05:27
tonibagur, Thank you very much!

I have done build kivy with your fix.

I hope your fix to be merged quickly.

**Comment by tonibagur** [comment] 2017-10-11 05:42
@xiushu53 a pleasure to help? @mbrockman1 my changes are not yet merged, did yow pull the branch xcode9_osx10_12 of my fork?
git pull -b xcode9_osx10_12 https://github.com/tonibagur/kivy-ios
In case of yes, may be the problem is with cython version? I see that you are using the version 0.25 instead of 0.23 as said in the readme....

**Comment by mbrockman1** [comment] 2017-10-11 12:37
Sorry about that, yes it works now after I switched to Cython 0.23!
For clarification, this branch is working on macOS 10.13, Cython 0.23 on your branch.

**Comment by mbrockman1** [comment] 2017-10-11 16:13
@xiushu53  can you explain how you were able to build kivy? I am still struggling to get it to work. Maybe it has something to do with
"*When the xcode project is created, in order to get kivy working you have to manually add the following frameworks:

    CoreMotion
    libz
    libsqlite3"
which I don't know how to do.

**Comment by xiushu53** [comment] 2017-10-13 00:59
@mbrockman1 

I fixed kivy-ios files on my local by hand. refer to [https://github.com/kivy/kivy-ios/pull/268/commits/de7abcbb5963d45645ca00343acedec755f38de8](https://github.com/kivy/kivy-ios/pull/268/commits/de7abcbb5963d45645ca00343acedec755f38de8).

Then, I built kivy well.

**Closed** 2018-11-17 10:41 UTC
