### ISSUE TITLE
Working app crash on iOS 17

### ISSUE THREAD

**Issue by sysnux** [kivy/kivy-ios#864] opened 2023-09-14 22:09 UTC
My app has been working on iOS for a few years:
https://apps.apple.com/fr/app/polyapp-banque-de-polyn%C3%A9sie/id1570748267

But tests on iOS-17 beta show it is now crashing on startup.
I have rebuilt the app with latest Xcode-14 as requested, but still same crash on startup, without indication on what is wrong.

I could not find any hints on Kivy forums, is this a known problem? Has anyone tried iOS-17?

**Comment by misl6** [comment] 2023-09-15 16:44
Hi @sysnux !

On iOS 17 Simulator, with XCode 15 RC1, everything works like a charm.
- Is your app using any feature that has been removed in iOS 17?
- What happens when the app is run via XCode in debug mode?

**Comment by sysnux** [comment] 2023-09-18 17:20
Hi @misl6,
Thanks for your reply.
I was able to confirm my app works fine on iOS 17 simulator, with Xcode 15.0 (15A240d). I just had to change "User Script Sandboxing" to No.
Still, I does not work on iPhone :(

**Comment by sysnux** [comment] 2023-09-21 00:36
Hi @misl6

The application is now working fine, and an iOS17 compatible version is on the Apple Store, yeah!

The crash was actually in plyer. My code is using uniqueid.id from plyer, which generates TypeError on iOS17 iPhone only (not on Simulator):
```
  File "/.../site-packages/plyer/platforms/ios/uniqueid.py", line 19, in _get_uid
     uuid = UIDevice.currentDevice().identifierForVendor.UUIDString()
 TypeError: 'Swift.__StringStorage' object is not callable
```
I changed my code to:
```
       try:
            self.uniqueid = uniqueid.id
        except (TypeError, NotImplementedError, NameError):
```
Concerning "User Script Sandboxingg", I still have the error if I enable it:
`Sandbox: rsync deny file-read-data /Users/..../polyapp-ios/YourApp`
Maybe specific to this application, not sure why.

You can close the issue, thanks!

**Comment by misl6** [comment] 2023-09-21 05:51
@sysnux can you please target this specific issue with a PR on plyer? 😃

**Comment by sysnux** [comment] 2023-09-21 17:39
Hi @misl6,

I can't test the fix, so PR is not possible, sorry.
I opened an issue instead: https://github.com/kivy/plyer/issues/773

Thanks for your support!

**Comment by Julian-O** [comment] 2023-10-29 03:44
Closing as duplicate of Plyer issue.

**Closed by Julian-O** 2023-10-29 03:44 UTC
