### ISSUE TITLE
ImportError: PyInit_interval

### ISSUE THREAD

**Issue by mhdemd** [kivy/kivy-ios#788] opened 2023-03-30 16:11 UTC
Hi everyone
I am developing an application that uses Pandas. I get this error when running:

"ImportError: dynamic module does not define module export function (PyInit_interval)"

can you help me, please

## Versions:
Python:3.9.6
OS:macOS Ventura 13.2.1 (on VMware)
pandas: 1.5.3
numpy:  1.24.2
pytz: 2023.3
python-dateutil: 2.8.2 
six: 1.16.0

**Comment by mhdemd** [comment] 2023-04-01 12:15
2023-03-31 23:35:33.093539-0700 digi1[1174:13058] [SceneConfiguration] Info.plist contained no UIScene configuration dictionary (looking for configuration named "(no name)")

2023-03-31 23:35:33.094159-0700 digi1[1174:13058] [SceneConfiguration] Info.plist contained no UIScene configuration dictionary (looking for configuration named "(no name)")

2023-03-31 23:35:33.587764-0700 digi1[1174:13058] Available orientation: KIVY_ORIENTATION=LandscapeLeft LandscapeRight Portrait PortraitUpsideDown

2023-03-31 23:35:33.588394-0700 digi1[1174:13058] Initializing python

<string>:1: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses

2023-03-31 23:35:34.271002-0700 digi1[1174:13058] Running main.py: /Users/me6/Library/Developer/CoreSimulator/Devices/FD6E5158-7D3D-4AE1-BE45-BE434CB6EAF8/data/Containers/Bundle/Application/6E4F8092-526F-40CF-A6D9-D3E79D8FE281/digi1.app/YourApp/main.pyc

[INFO   ] [Logger      ] Record log in /Users/me6/Library/Developer/CoreSimulator/Devices/FD6E5158-7D3D-4AE1-BE45-BE434CB6EAF8/data/Containers/Data/Application/7BA58332-1856-45AE-8905-6D53DB407859/Documents/.kivy/logs/kivy_23-03-31_1.txt

[INFO   ] [Kivy        ] v2.2.0.dev0

[INFO   ] [Kivy        ] Installed at "/Users/me6/Library/Developer/CoreSimulator/Devices/FD6E5158-7D3D-4AE1-BE45-BE434CB6EAF8/data/Containers/Bundle/Application/6E4F8092-526F-40CF-A6D9-D3E79D8FE281/digi1.app/lib/python3.10/site-packages/kivy/__init__.py"

[INFO   ] [Python      ] v3.10.10 (main, Mar 30 2023, 06:07:26) [Clang 14.0.0 (clang-1400.0.29.202)]

[INFO   ] [Python      ] Interpreter at "/Users/me6/Library/Developer/CoreSimulator/Devices/FD6E5158-7D3D-4AE1-BE45-BE434CB6EAF8/data/Containers/Bundle/Application/6E4F8092-526F-40CF-A6D9-D3E79D8FE281/digi1.app/digi1"

[INFO   ] [Logger      ] Purge log fired. Processing...

[INFO   ] [Logger      ] Purge finished!

[INFO   ] [Factory     ] 189 symbols loaded

[INFO   ] [Image       ] Providers: img_imageio, img_tex, img_sdl2 (img_dds, img_ffpyplayer, img_pil ignored)

[INFO   ] [Text        ] Provider: sdl2

[INFO   ] [Loader      ] using a thread pool of 2 workers

[INFO   ] [Window      ] Provider: sdl2

2023-03-31 23:35:36.884529-0700 digi1[1174:13058] You need UIApplicationSupportsIndirectInputEvents in your Info.plist for mouse support

[INFO   ] [GL          ] Using the "OpenGL ES 2" graphics system

[INFO   ] [GL          ] Backend used <sdl2>

[INFO   ] [GL          ] OpenGL version <b'OpenGL ES 2.0 APPLE-20.0.39'>

[INFO   ] [GL          ] OpenGL vendor <b'Apple Inc.'>

[INFO   ] [GL          ] OpenGL renderer <b'Apple Software Renderer'>

[INFO   ] [GL          ] OpenGL parsed version: 2, 0

[INFO   ] [GL          ] Shading version <b'OpenGL ES GLSL ES 1.00'>

[INFO   ] [GL          ] Texture max size <4096>

[INFO   ] [GL          ] Texture max units <8>

[INFO   ] [Window      ] auto add sdl2 input provider

[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked

[INFO   ] [KivyMD      ] 1.1.1, git-Unknown, 2023-03-30 (installed at "/Users/me6/Library/Developer/CoreSimulator/Devices/FD6E5158-7D3D-4AE1-BE45-BE434CB6EAF8/data/Containers/Bundle/Application/6E4F8092-526F-40CF-A6D9-D3E79D8FE281/digi1.app/lib/python3.10/site-packages/kivymd/__init__.py")

Got dlopen error on Foundation: dlopen(/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation, 0x0001): tried: '/Users/me6/Library/Developer/Xcode/DerivedData/digi1-fplnuczlkqgqmxdbvucaxiiqxchc/Build/Products/Debug-iphonesimulator/Foundation.framework/Versions/Current/Foundation' (errno=2), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation' (errno=2), '/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation' (errno=2, not in dyld cache), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation' (errno=2), '/Users/me6/Library/Developer/Xcode/DerivedData/digi1-fplnuczlkqgqmxdbvucaxiiqxchc/Build/Products/Debug-iphonesimulator/Foundation.framework/Versions/C/Foundation' (errno=2), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation' (errno=2), '/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation' (errno=2, not in dyld cache), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation' (errno=2)

Got fallback dlopen error on Foundation: dlopen(/Groups/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation, 0x0001): tried: '/Users/me6/Library/Developer/Xcode/DerivedData/digi1-fplnuczlkqgqmxdbvucaxiiqxchc/Build/Products/Debug-iphonesimulator/Foundation.framework/Versions/Current/Foundation' (errno=2), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/Groups/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation' (errno=2), '/Groups/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation' (errno=2), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation' (errno=2)

 Traceback (most recent call last):

   File "<string>", line 44, in load_module

   File "/Users/me6/kivy-ios/dist/root/python3/lib/python3.10/imp.py", line 343, in load_dynamic

   File "<frozen importlib._bootstrap>", line 719, in _load

   File "<frozen importlib._bootstrap>", line 674, in _load_unlocked

   File "<frozen importlib._bootstrap>", line 571, in module_from_spec

   File "<frozen importlib._bootstrap_external>", line 1176, in create_module

   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed

 ImportError: dynamic module does not define module export function (PyInit_pandas__libs_interval)

 

 During handling of the above exception, another exception occurred:

 

 Traceback (most recent call last):

   File "/Users/me6/kivy-ios/digi1-ios/YourApp/main.py", line 31, in <module>

   File "/Users/me6/Library/Developer/CoreSimulator/Devices/FD6E5158-7D3D-4AE1-BE45-BE434CB6EAF8/data/Containers/Bundle/Application/6E4F8092-526F-40CF-A6D9-D3E79D8FE281/digi1.app/lib/python3.10/site-packages/pandas/__init__.py", line 22, in <module>

     from pandas.compat import is_numpy_dev as _is_numpy_dev  # pyright: ignore # noqa:F401

   File "/Users/me6/Library/Developer/CoreSimulator/Devices/FD6E5158-7D3D-4AE1-BE45-BE434CB6EAF8/data/Containers/Bundle/Application/6E4F8092-526F-40CF-A6D9-D3E79D8FE281/digi1.app/lib/python3.10/site-packages/pandas/compat/__init__.py", line 18, in <module>

     from pandas.compat.numpy import (

   File "/Users/me6/Library/Developer/CoreSimulator/Devices/FD6E5158-7D3D-4AE1-BE45-BE434CB6EAF8/data/Containers/Bundle/Application/6E4F8092-526F-40CF-A6D9-D3E79D8FE281/digi1.app/lib/python3.10/site-packages/pandas/compat/numpy/__init__.py", line 4, in <module>

     from pandas.util.version import Version

   File "/Users/me6/Library/Developer/CoreSimulator/Devices/FD6E5158-7D3D-4AE1-BE45-BE434CB6EAF8/data/Containers/Bundle/Application/6E4F8092-526F-40CF-A6D9-D3E79D8FE281/digi1.app/lib/python3.10/site-packages/pandas/util/__init__.py", line 2, in <module>

     from pandas.util._decorators import (  # noqa:F401

   File "/Users/me6/Library/Developer/CoreSimulator/Devices/FD6E5158-7D3D-4AE1-BE45-BE434CB6EAF8/data/Containers/Bundle/Application/6E4F8092-526F-40CF-A6D9-D3E79D8FE281/digi1.app/lib/python3.10/site-packages/pandas/util/_decorators.py", line 14, in <module>

     from pandas._libs.properties import cache_readonly

   File "/Users/me6/Library/Developer/CoreSimulator/Devices/FD6E5158-7D3D-4AE1-BE45-BE434CB6EAF8/data/Containers/Bundle/Application/6E4F8092-526F-40CF-A6D9-D3E79D8FE281/digi1.app/lib/python3.10/site-packages/pandas/_libs/__init__.py", line 13, in <module>

     from pandas._libs.interval import Interval

   File "<string>", line 48, in load_module

   File "/Users/me6/kivy-ios/dist/root/python3/lib/python3.10/imp.py", line 343, in load_dynamic

 ImportError: dynamic module does not define module export function (PyInit_interval)

2023-03-31 23:35:39.014971-0700 digi1[1174:13058] Application quit abnormally!

2023-03-31 23:35:39.111081-0700 digi1[1174:13058] Leaving

**Comment by alwwwd** [comment] 2023-04-01 12:33
send Xcode log pls

**Comment by mhdemd** [comment] 2023-04-01 13:31
I don't know how to get error output from xcode, can you help me?

Sent from Yahoo Mail on Android 
 
  On Sat, 1 Apr 2023 at 17:04, alex ***@***.***> wrote:   


send Xcode log pls

**Comment by misl6** [comment] 2023-04-02 11:14
Duplicate of #616

**Closed by misl6** 2023-04-02 11:14 UTC
