### ISSUE TITLE
Toolchain build failed on OSX Xcode 8, libffi depends on undefined mkostemp function

### ISSUE THREAD

**Issue by TimSC** [kivy/kivy-ios#211] opened 2016-09-18 15:25 UTC
Not sure what what is going on here... OSX 10.11.6, Xcode 8.0 (8A218a), using  c7624becbd122d991112f37ee01cfa3a9b6a040f

```
$ ./toolchain.py build kivy
Want to build ['kivy']
Loaded recipe kivy (depends of ['python', 'sdl2', 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf', 'ios'], optional are [])
Loaded recipe python (depends of ['hostpython', 'libffi'], optional are ['openssl'])
Loaded recipe sdl2 (depends of [], optional are [])
Loaded recipe sdl2_image (depends of ['sdl2'], optional are [])
Loaded recipe sdl2_mixer (depends of ['sdl2'], optional are [])
Loaded recipe sdl2_ttf (depends of ['sdl2', 'freetype'], optional are [])
Loaded recipe ios (depends of ['python'], optional are [])
Loaded recipe hostpython (depends of ['hostlibffi'], optional are [])
Loaded recipe libffi (depends of [], optional are [])
Loaded recipe freetype (depends of [], optional are [])
Loaded recipe hostlibffi (depends of [], optional are [])
Build order is ['freetype', 'hostlibffi', 'libffi', 'sdl2', 'hostpython', 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf', 'python', 'ios', 'kivy']
Include dir added: {arch.arch}/freetype
Include dir added: {arch.arch}/hostlibffi
Include dir added: {arch.arch}/libffi
Include dir added: common/sdl2
Global: hostpython located at /Users/Tim/dev/kivy-ios/dist/hostpython/bin/python
Global: hostpgen located at /Users/Tim/dev/kivy-ios/dist/hostpython/bin/pgen
Include dir added: common/sdl2_image
Include dir added: common/sdl2_mixer
Include dir added: common/sdl2_ttf
# (ignored) Download freetype
# (ignored) Extract freetype
# (ignored) Build_all freetype
# (ignored) Download hostlibffi
# (ignored) Extract hostlibffi
Build hostlibffi for x86_64 (filtered)
# (ignored) Build hostlibffi
# (ignored) Download libffi
# (ignored) Extract libffi
# (ignored) Build_all libffi
# (ignored) Download sdl2
# (ignored) Extract sdl2
# (ignored) Build_all sdl2
# (ignored) Download hostpython
# (ignored) Extract hostpython
Build_all hostpython
Build hostpython for x86_64 (filtered)
# (ignored) Build hostpython
Install include files for hostpython
# (ignored) Install_include hostpython
Install frameworks for hostpython
# (ignored) Install_frameworks hostpython
Install sources for hostpython
# (ignored) Install_sources hostpython
Install hostpython
Makefile:1392: warning: overriding commands for target `Modules/posixmodule.o'
Makefile:1284: warning: ignoring old commands for target `Modules/posixmodule.o'
Makefile:1393: warning: overriding commands for target `Modules/posixmodule.so'
Makefile:1285: warning: ignoring old commands for target `Modules/posixmodule.so'
Makefile:1394: warning: overriding commands for target `Modules/errnomodule.o'
Makefile:1286: warning: ignoring old commands for target `Modules/errnomodule.o'
Makefile:1395: warning: overriding commands for target `Modules/errnomodule.so'
Makefile:1287: warning: ignoring old commands for target `Modules/errnomodule.so'
Makefile:1396: warning: overriding commands for target `Modules/pwdmodule.o'
Makefile:1288: warning: ignoring old commands for target `Modules/pwdmodule.o'
Makefile:1397: warning: overriding commands for target `Modules/pwdmodule.so'
Makefile:1289: warning: ignoring old commands for target `Modules/pwdmodule.so'
Makefile:1398: warning: overriding commands for target `Modules/_sre.o'
Makefile:1290: warning: ignoring old commands for target `Modules/_sre.o'
Makefile:1399: warning: overriding commands for target `Modules/_sre.so'
Makefile:1291: warning: ignoring old commands for target `Modules/_sre.so'
Makefile:1400: warning: overriding commands for target `Modules/_codecsmodule.o'
Makefile:1292: warning: ignoring old commands for target `Modules/_codecsmodule.o'
Makefile:1401: warning: overriding commands for target `Modules/_codecsmodule.so'
Makefile:1293: warning: ignoring old commands for target `Modules/_codecsmodule.so'
Makefile:1402: warning: overriding commands for target `Modules/_weakref.o'
Makefile:1310: warning: ignoring old commands for target `Modules/_weakref.o'
Makefile:1403: warning: overriding commands for target `Modules/_weakref.so'
Makefile:1311: warning: ignoring old commands for target `Modules/_weakref.so'
Makefile:1404: warning: overriding commands for target `Modules/zipimport.o'
Makefile:1294: warning: ignoring old commands for target `Modules/zipimport.o'
Makefile:1405: warning: overriding commands for target `Modules/zipimport.so'
Makefile:1295: warning: ignoring old commands for target `Modules/zipimport.so'
Makefile:1406: warning: overriding commands for target `Modules/symtablemodule.o'
Makefile:1296: warning: ignoring old commands for target `Modules/symtablemodule.o'
Makefile:1407: warning: overriding commands for target `Modules/_symtablemodule.so'
Makefile:1297: warning: ignoring old commands for target `Modules/_symtablemodule.so'
Makefile:1408: warning: overriding commands for target `Modules/xxsubtype.o'
Makefile:1353: warning: ignoring old commands for target `Modules/xxsubtype.o'
Makefile:1409: warning: overriding commands for target `Modules/xxsubtype.so'
Makefile:1354: warning: ignoring old commands for target `Modules/xxsubtype.so'
clang -Qunused-arguments -fcolor-diagnostics -lsqlite3 -lffi -L/Users/Tim/dev/kivy-ios/dist/hostlibffi/usr/local/lib  -o python.exe \
            Modules/python.o \
            libpython2.7.a -ldl  -framework CoreFoundation -L/Users/Tim/dev/kivy-ios/dist/hostpython/lib -lz                      
ld: warning: directory not found for option '-L/Users/Tim/dev/kivy-ios/dist/hostpython/lib'
Undefined symbols for architecture x86_64:
  "_mkostemp", referenced from:
      _open_temp_exec_file_dir in libffi.a(closures.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [python.exe] Error 1
Traceback (most recent call last):
  File "./toolchain.py", line 1311, in <module>
    ToolchainCL()
  File "./toolchain.py", line 1082, in __init__
    getattr(self, args.command)()
  File "./toolchain.py", line 1106, in build
    build_recipes(args.recipe, ctx)
  File "./toolchain.py", line 974, in build_recipes
    recipe.execute()
  File "/Users/Tim/dev/kivy-ios/toolchain.py", line 586, in execute
    self.build_all()
  File "/Users/Tim/dev/kivy-ios/toolchain.py", line 56, in _cache_execution
    f(self, *args, **kwargs)
  File "/Users/Tim/dev/kivy-ios/toolchain.py", line 698, in build_all
    self.install()
  File "/Users/Tim/dev/kivy-ios/recipes/hostpython/__init__.py", line 86, in install
    _env=build_env)
  File "/Users/Tim/dev/kivy-ios/toolchain.py", line 39, in shprint
    for line in command(*args, **kwargs):
  File "./tools/external/sh.py", line 565, in next
    self.wait()
  File "./tools/external/sh.py", line 500, in wait
    self.handle_command_exit_code(exit_code)
  File "./tools/external/sh.py", line 516, in handle_command_exit_code
    raise exc(self.ran, self.process.stdout, self.process.stderr)
sh.ErrorReturnCode_2: 

  RAN: '/usr/bin/make -C /Users/Tim/dev/kivy-ios/build/hostpython/x86_64/Python-2.7.1 bininstall inclinstall'

  STDOUT:
Makefile:1392: warning: overriding commands for target `Modules/posixmodule.o'
Makefile:1284: warning: ignoring old commands for target `Modules/posixmodule.o'
Makefile:1393: warning: overriding commands for target `Modules/posixmodule.so'
Makefile:1285: warning: ignoring old commands for target `Modules/posixmodule.so'
Makefile:1394: warning: overriding commands for target `Modules/errnomodule.o'
Makefile:1286: warning: ignoring old commands for target `Modules/errnomodule.o'
Makefile:1395: warning: overriding commands for target `Modules/errnomodule.so'
Makefile:1287: warning: ignoring old commands for target `Modules/errnomodule.so'
Makefile:1396: warning: overriding commands for target `Modules/pwdmodule.o'
Makefile:1288: warning: ignor... (2782 more, please see e.stdout)

  STDERR:
```

This might be useful:

```
$ ./toolchain.py recipes
audiostream  master  
click        master  
distribute   0.7.3   
ffmpeg       2.6.3   
ffpyplayer   v3.2    
flask        master  
freetype     2.5.5   
host_setuptools None    
hostlibffi   3.2.1   
hostpython   2.7.1   
ios          master  
itsdangerous master  
jinja2       master  
kivy         1.9.1   
libffi       3.2.1   
libjpeg      v9a     
markupsafe   master  
moodstocks   4.1.5   
numpy        1.9.1   
openssl      1.0.2h  
photolibrary master  
pil          2.8.2   
pkgresources None    
plyer        master  
pycrypto     2.6.1   
pymoodstocks master  
pyobjus      master  
python       2.7.1   
pyyaml       3.11    
sdl2         iOS-improvements
sdl2_image   2.0.0   
sdl2_mixer   2.0.0   
sdl2_ttf     2.0.12  
werkzeug     master 
```

I notice when libffi is configuring, it says:

```
checking for mkostemp... yes
```

Is that right? The line in libffi that calls mkostemp : https://github.com/libffi/libffi/blob/5d0365c605c472f40d1195cf7ba04ae08e360cb7/src/closures.c#L502
##

**Comment by cruor99** [comment] 2016-09-19 12:48
I am experiencing the same issue. I think it might be related to the recent xcode update, so I'll try to go back to xcode 7 and see what happens then. I'll report back with what I find.

**Comment by TimSC** [comment] 2016-09-19 18:09
Thanks for the work around.

When I build libffi v3.2.1 directly from source, it works fine. That might indicate it is a problem with an out of date configure from autotools...

```
Tims-MacBook-Pro:dev Tim$ git clone https://github.com/libffi/libffi.git
Cloning into 'libffi'...
remote: Counting objects: 10587, done.
remote: Total 10587 (delta 0), reused 0 (delta 0), pack-reused 10586
Receiving objects: 100% (10587/10587), 6.77 MiB | 1.17 MiB/s, done.
Resolving deltas: 100% (6581/6581), done.
Checking connectivity... done.
Tims-MacBook-Pro:dev Tim$ cd libffi/
Tims-MacBook-Pro:libffi Tim$ git checkout v3.2.1
Note: checking out 'v3.2.1'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 20562ac... Fix for AArch64. Release as 3.2.1.
Tims-MacBook-Pro:libffi Tim$ git checkout -b v3.2.1
Switched to a new branch 'v3.2.1'
Tims-MacBook-Pro:libffi Tim$ ./autogen.sh 
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: running: glibtoolize --copy --force
glibtoolize: putting auxiliary files in '.'.
glibtoolize: copying file './ltmain.sh'
glibtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
glibtoolize: copying file 'm4/libtool.m4'
glibtoolize: copying file 'm4/ltoptions.m4'
glibtoolize: copying file 'm4/ltsugar.m4'
glibtoolize: copying file 'm4/ltversion.m4'
glibtoolize: copying file 'm4/lt~obsolete.m4'
autoreconf: running: /usr/local/Cellar/autoconf/2.69/bin/autoconf --force
autoreconf: running: /usr/local/Cellar/autoconf/2.69/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:31: installing './compile'
configure.ac:8: installing './config.guess'
configure.ac:8: installing './config.sub'
configure.ac:19: installing './install-sh'
configure.ac:19: installing './missing'
Makefile.am: installing './depcomp'
Makefile.am:56: installing './mdate-sh'
autoreconf: Leaving directory `.'
Tims-MacBook-Pro:libffi Tim$ ./configure
checking build system type... x86_64-apple-darwin15.6.0
checking host system type... x86_64-apple-darwin15.6.0
checking target system type... x86_64-apple-darwin15.6.0
continue configure in default builddir "./x86_64-apple-darwin15.6.0"
....exec /bin/sh .././configure "--srcdir=.." "--enable-builddir=x86_64-apple-darwin15.6.0" "darwin15.6.0"
checking build system type... x86_64-apple-darwin15.6.0
checking host system type... x86_64-apple-darwin15.6.0
checking target system type... x86_64-apple-darwin15.6.0
checking for gsed... sed
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... ../install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking dependency style of gcc... gcc3
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld
checking if the linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) is GNU ld... no
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 196608
checking how to convert x86_64-apple-darwin15.6.0 file names to x86_64-apple-darwin15.6.0 format... func_convert_file_noop
checking how to convert x86_64-apple-darwin15.6.0 file names to toolchain format... func_convert_file_noop
checking for /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld option to reload object files... -r
checking for objdump... no
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... no
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
checking for dsymutil... dsymutil
checking for nmedit... nmedit
checking for lipo... lipo
checking for otool... otool
checking for otool64... no
checking for -single_module linker flag... yes
checking for -exported_symbols_list linker flag... yes
checking for -force_load linker flag... yes
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... yes
checking for gcc option to produce PIC... -fno-common -DPIC
checking if gcc PIC flag -fno-common -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin15.6.0 dyld
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld
checking if the linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) is GNU ld... no
checking whether the g++ linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) supports shared libraries... yes
checking for g++ option to produce PIC... -fno-common -DPIC
checking if g++ PIC flag -fno-common -DPIC works... yes
checking if g++ static flag -static works... no
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin15.6.0 dyld
checking how to hardcode library paths into programs... immediate
checking size of size_t... 8
checking for C compiler vendor... clang

********************************************************
* WARNING: Don't know the best CFLAGS for this system  *
* Use ./configure CFLAGS=... to specify your own flags *
* (otherwise, a default of CFLAGS=-O3 will be used)    *
********************************************************

checking whether C compiler accepts -O3... yes
checking CFLAGS for maximum warnings... -Wall
checking whether to enable maintainer-specific portions of Makefiles... no
checking sys/mman.h usability... yes
checking sys/mman.h presence... yes
checking for sys/mman.h... yes
checking for mmap... yes
checking for mkostemp... no
checking for sys/mman.h... (cached) yes
checking for mmap... (cached) yes
checking whether read-only mmap of a plain file works... yes
checking whether mmap from /dev/zero works... no
checking for MAP_ANON(YMOUS)... yes
checking whether mmap with MAP_ANON(YMOUS) works... yes
checking for ANSI C header files... (cached) yes
checking for memcpy... yes
checking for size_t... yes
checking for working alloca.h... yes
checking for alloca... yes
checking size of double... 8
checking size of long double... 16
checking whether byte ordering is bigendian... no
checking assembler .cfi pseudo-op support... yes
checking for _ prefix in compiled symbols... yes
checking whether .eh_frame section should be read-only... expr: syntax error
no
checking for __attribute__((visibility("hidden")))... no
clang: error: unsupported option '-print-multi-os-directory'
clang: error: no input files
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating include/Makefile
config.status: creating include/ffi.h
config.status: creating Makefile
config.status: creating testsuite/Makefile
config.status: creating man/Makefile
config.status: creating libffi.pc
config.status: creating fficonfig.h
config.status: linking ../src/x86/ffitarget.h to include/ffitarget.h
config.status: executing buildir commands
config.status: create top_srcdir/Makefile guessed from local Makefile
config.status: buggy sed found - it deletes tab in "a" text parts
config.status: build in x86_64-apple-darwin15.6.0 (HOST=)
config.status: executing depfiles commands
config.status: executing libtool commands
config.status: executing include commands
config.status: executing src commands
Tims-MacBook-Pro:libffi Tim$ 
```

**Comment by kdheepak** [comment] 2016-10-29 13:22
@TimSC are you able to build `libffi` from source and use Xcode 8?

**Comment by TimSC** [comment] 2016-10-29 13:42
@kdheepak I can build libffi but I don't really know do to get the build tools to pick it up with Xcode 8. It's not really high enough on my priority list at the moment.

**Comment by kdheepak** [comment] 2016-10-29 14:26
I see. Are you deploying to iOS10? I'm unable to use Xcode7.x to deploy to iOS10, and I was wondering if this was an isolated issue.

**Comment by TimSC** [comment] 2016-10-29 15:02
I can't see how target iOS10 at the moment, but I'm not really a mac expert!

**Comment by cruor99** [comment] 2016-11-01 11:18
You can target iOS10 by grabbing the SDK from xcode8, and dropping it into xcode 7, while using xcode 7 as a workaround for this.

The sdk's are located in Developer/Platforms/iphoneos.platform/sdk's and /devicesupport. Just copy the ios 10 related stuff from xcode 8 from there, and drop it into xcode 7. Tedious workaround, but at least it works for now.

**Comment by kdheepak** [comment] 2016-11-02 03:05
Alternatively, you can run `./toolchain.py build kivy` with Xcode7 and compile the project using Xcode8.1 for iOS10. From initial testing it seems to work, although I'm unable to get print statements or logging to show up in the Xcode console. @cruor99 suggestion is great too, since you will only need one version of Xcode.

**Comment by Zen-CODE** [comment] 2016-11-05 21:51
@kdheepak. Try this fix for the XCode output. That would be made to your 'main.m' file...

https://github.com/kivy/kivy-ios/pull/219/files

I've successfully build libffi using Xcode 8.0 and 8.1, so not sure what the original error here....

**Comment by WillyWinkel** [comment] 2016-11-06 20:42
same error with Xcode Version 8.0 and 10.11.6

**Comment by Zen-CODE** [comment] 2016-11-23 19:14
@kdheepak. Please re-try with the latest pull. You should get print/logging showing then.

@TimSC. You can always try dropping the binary you built into kivy-ios/dist/lib and see if that works? But I really would like to get to the bottom of the error here.

This seems like a library linking issue here. So I think the first step here is to cover assumptions. Can you build and run a pure objective-c/swift app and build it for all architectures? Let's just establish that your base XCode install is up and running as the error is generated by clang itself (not a kivy tool).

**Comment by akshayaurora** [comment] 2016-11-23 20:35
I can confirm compiling with Xcode 8 and 8.1 works here. just like for @Zen-CODE . Just make sure to update your os and your Xcode and the command line tools.

**Comment by TimSC** [comment] 2016-11-24 00:32
@Zen-CODE I don't have time to follow this up at the moment, but I will reopen this issue if it recurs.

**Comment by Zen-CODE** [comment] 2016-11-24 06:03
Great thank. I'm going to close it for now. If it recurs, please post here and we'll look at re-opening it.

Peace out

**Closed by Zen-CODE** 2016-11-24 06:03 UTC

**Comment by libbil** [comment] 2017-02-10 10:47
For what it's worth i get the exact same issue running xcode 8.2.1 and the latest build of kivy-ios from github. I'll try building using xcode 7.3 and see what happens.
This guide told be how to install older versions of xcode:[http://iosdevelopertips.com/xcode/install-multiple-versions-of-xcode.html]( http://iosdevelopertips.com/xcode/install-multiple-versions-of-xcode.html)

**Comment by erikwiffin** [comment] 2017-03-16 04:23
I'm also seeing this issue.

Latest kivy-ios from github.
Python 2.7.11
Xcode Version 8.2.1 (8C1002)

```
$ ./toolchain.py build python
Want to build ['python']
Loaded recipe python (depends of ['hostpython', 'libffi'], optional are ['openssl'])
Loaded recipe hostpython (depends of ['hostlibffi'], optional are ['openssl'])
Loaded recipe libffi (depends of [], optional are [])
Loaded recipe hostlibffi (depends of [], optional are [])
Build order is ['hostlibffi', 'libffi', 'hostpython', 'python']
Include dir added: {arch.arch}/hostlibffi
Include dir added: {arch.arch}/libffi
Global: hostpython located at /Users/erik/Documents/Projects/dino-game/.buildozer/ios/platform/kivy-ios/dist/hostpython/bin/python
Global: hostpgen located at /Users/erik/Documents/Projects/dino-game/.buildozer/ios/platform/kivy-ios/dist/hostpython/bin/pgen
# (ignored) Download hostlibffi
# (ignored) Extract hostlibffi
Build hostlibffi for x86_64 (filtered)
# (ignored) Build hostlibffi
# (ignored) Download libffi
# (ignored) Extract libffi
# (ignored) Build_all libffi
# (ignored) Download hostpython
# (ignored) Extract hostpython
Build_all hostpython
Build hostpython for x86_64 (filtered)
# (ignored) Build hostpython
Install include files for hostpython
# (ignored) Install_include hostpython
Install frameworks for hostpython
# (ignored) Install_frameworks hostpython
Install sources for hostpython
# (ignored) Install_sources hostpython
Install hostpython
Makefile:1392: warning: overriding commands for target `Modules/posixmodule.o'
Makefile:1284: warning: ignoring old commands for target `Modules/posixmodule.o'
Makefile:1393: warning: overriding commands for target `Modules/posixmodule.so'
Makefile:1285: warning: ignoring old commands for target `Modules/posixmodule.so'
Makefile:1394: warning: overriding commands for target `Modules/errnomodule.o'
Makefile:1286: warning: ignoring old commands for target `Modules/errnomodule.o'
Makefile:1395: warning: overriding commands for target `Modules/errnomodule.so'
Makefile:1287: warning: ignoring old commands for target `Modules/errnomodule.so'
Makefile:1396: warning: overriding commands for target `Modules/pwdmodule.o'
Makefile:1288: warning: ignoring old commands for target `Modules/pwdmodule.o'
Makefile:1397: warning: overriding commands for target `Modules/pwdmodule.so'
Makefile:1289: warning: ignoring old commands for target `Modules/pwdmodule.so'
Makefile:1398: warning: overriding commands for target `Modules/_sre.o'
Makefile:1290: warning: ignoring old commands for target `Modules/_sre.o'
Makefile:1399: warning: overriding commands for target `Modules/_sre.so'
Makefile:1291: warning: ignoring old commands for target `Modules/_sre.so'
Makefile:1400: warning: overriding commands for target `Modules/_codecsmodule.o'
Makefile:1292: warning: ignoring old commands for target `Modules/_codecsmodule.o'
Makefile:1401: warning: overriding commands for target `Modules/_codecsmodule.so'
Makefile:1293: warning: ignoring old commands for target `Modules/_codecsmodule.so'
Makefile:1402: warning: overriding commands for target `Modules/_weakref.o'
Makefile:1310: warning: ignoring old commands for target `Modules/_weakref.o'
Makefile:1403: warning: overriding commands for target `Modules/_weakref.so'
Makefile:1311: warning: ignoring old commands for target `Modules/_weakref.so'
Makefile:1404: warning: overriding commands for target `Modules/zipimport.o'
Makefile:1294: warning: ignoring old commands for target `Modules/zipimport.o'
Makefile:1405: warning: overriding commands for target `Modules/zipimport.so'
Makefile:1295: warning: ignoring old commands for target `Modules/zipimport.so'
Makefile:1406: warning: overriding commands for target `Modules/symtablemodule.o'
Makefile:1296: warning: ignoring old commands for target `Modules/symtablemodule.o'
Makefile:1407: warning: overriding commands for target `Modules/_symtablemodule.so'
Makefile:1297: warning: ignoring old commands for target `Modules/_symtablemodule.so'
Makefile:1408: warning: overriding commands for target `Modules/xxsubtype.o'
Makefile:1353: warning: ignoring old commands for target `Modules/xxsubtype.o'
Makefile:1409: warning: overriding commands for target `Modules/xxsubtype.so'
Makefile:1354: warning: ignoring old commands for target `Modules/xxsubtype.so'
clang -Qunused-arguments -fcolor-diagnostics -lsqlite3 -lffi -L/Users/erik/Documents/Projects/dino-game/.buildozer/ios/platform/kivy-ios/dist/hostlibffi/usr/local/lib  -o python.exe \
			Modules/python.o \
			libpython2.7.a -ldl  -framework CoreFoundation -L/Users/erik/Documents/Projects/dino-game/.buildozer/ios/platform/kivy-ios/dist/hostpython/lib -lz
ld: warning: directory not found for option '-L/Users/erik/Documents/Projects/dino-game/.buildozer/ios/platform/kivy-ios/dist/hostpython/lib'
Undefined symbols for architecture x86_64:
  "_mkostemp", referenced from:
      _open_temp_exec_file_dir in libffi.a(closures.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [python.exe] Error 1
Traceback (most recent call last):
  File "./toolchain.py", line 1318, in <module>
    ToolchainCL()
  File "./toolchain.py", line 1088, in __init__
    getattr(self, args.command)()
  File "./toolchain.py", line 1112, in build
    build_recipes(args.recipe, ctx)
  File "./toolchain.py", line 980, in build_recipes
    recipe.execute()
  File "/Users/erik/Documents/Projects/dino-game/.buildozer/ios/platform/kivy-ios/toolchain.py", line 590, in execute
    self.build_all()
  File "/Users/erik/Documents/Projects/dino-game/.buildozer/ios/platform/kivy-ios/toolchain.py", line 56, in _cache_execution
    f(self, *args, **kwargs)
  File "/Users/erik/Documents/Projects/dino-game/.buildozer/ios/platform/kivy-ios/toolchain.py", line 704, in build_all
    self.install()
  File "/Users/erik/Documents/Projects/dino-game/.buildozer/ios/platform/kivy-ios/recipes/hostpython/__init__.py", line 94, in install
    _env=build_env)
  File "/Users/erik/Documents/Projects/dino-game/.buildozer/ios/platform/kivy-ios/toolchain.py", line 39, in shprint
    for line in command(*args, **kwargs):
  File "./tools/external/sh.py", line 565, in next
    self.wait()
  File "./tools/external/sh.py", line 500, in wait
    self.handle_command_exit_code(exit_code)
  File "./tools/external/sh.py", line 516, in handle_command_exit_code
    raise exc(self.ran, self.process.stdout, self.process.stderr)
sh.ErrorReturnCode_2:

  RAN: '/usr/bin/make -C /Users/erik/Documents/Projects/dino-game/.buildozer/ios/platform/kivy-ios/build/hostpython/x86_64/Python-2.7.1 bininstall inclinstall'

  STDOUT:
Makefile:1392: warning: overriding commands for target `Modules/posixmodule.o'
Makefile:1284: warning: ignoring old commands for target `Modules/posixmodule.o'
Makefile:1393: warning: overriding commands for target `Modules/posixmodule.so'
Makefile:1285: warning: ignoring old commands for target `Modules/posixmodule.so'
Makefile:1394: warning: overriding commands for target `Modules/errnomodule.o'
Makefile:1286: warning: ignoring old commands for target `Modules/errnomodule.o'
Makefile:1395: warning: overriding commands for target `Modules/errnomodule.so'
Makefile:1287: warning: ignoring old commands for target `Modules/errnomodule.so'
Makefile:1396: warning: overriding commands for target `Modules/pwdmodule.o'
Makefile:1288: warning: ignor... (2932 more, please see e.stdout)

  STDERR:
```

**Comment by cruor99** [comment] 2017-03-16 07:42
What version of macOS are you on? This seems to be related when xcode is up to date,  but not on Sierra.

**Comment by erikwiffin** [comment] 2017-03-16 12:37
El Capitan, Version 10.11.6

So my workarounds are to either upgrade my OS or downgrade my Xcode?

**Comment by cruor99** [comment] 2017-03-16 12:38
As far as I know, yes. I think there's a thing further up the thread
showing how you can have two xcode versions side by side.

**Comment by erikwiffin** [comment] 2017-03-16 12:39
Okay, thanks!
