### ISSUE TITLE
Recipe for OpenCV

### ISSUE THREAD

**Issue by heimau** [kivy/kivy-ios#637] opened 2021-08-29 15:50 UTC
There is no recipe for OpenCV in Kivy-ios, do you know if this kind of recipe coming soon?

I already try to use OpenCV.Framework in Xcode project, but it does not work the right way.

**Comment by misl6** [comment] 2021-08-29 20:58
Unfortunately there's no ETA for opencv.
Thank you for opening the feature request.

**Comment by Julian-O** [comment] 2023-10-28 18:01
Closing as duplicate of #608

**Closed by Julian-O** 2023-10-28 18:01 UTC
Labels: recipes, feature request
