### ISSUE TITLE
tools/build-all.sh does not work on latest OS X

### ISSUE THREAD

**Issue by xapple** [kivy/kivy-ios#114] opened 2014-12-28 03:33 UTC
Hello ! I'm running OS X `10.10.1`, Xcode `6.1.1`, Kivy `1.8.0` and Cython `0.20.2`. So I just cloned this repository and executed `tools/build-all.sh`. But it does not work. This is a pity because the only reason I'm trying out kivy is to make an iOS application.... Any ideas what could solve the problem ?

The full output of the script is over 12'000 lines long, so I put it in a gist:

https://gist.github.com/xapple/04cbe6148754a748f886

**Comment by hanattaw** [comment] 2015-01-07 08:07
I'm running on OS X 10.10.2 , Xcode 6.1.1, Kivy 1.8.0 and Cython 0.21.1. 

Everthing work fine. Except i could not run my app on iOS simulator. And i don't have iOS device to test too.

**Comment by xapple** [comment] 2015-01-08 19:18
How can you be running Cython 0.21.1, as you can see [here](https://github.com/kivy/kivy/issues/2794) that would cause Kivy not too work. Also OS X 10.10.2 isn't released yet.

So no idea how to fix the problem ? The Kivy framework isn't so interesting without iOS support...

**Comment by jeffsenn** [comment] 2015-01-08 19:27
I think he means it builds (since he has no device to run on, he can't be running it!). It also *builds* for me with Cython 0.21.1 (in OS X 10.10.1/Xcode 6.6.1 -- or did a couple of weeks ago in both 1.8.0 and the dev-master), but then fails obscurely and fatally at runtime (see: #111 )

**Comment by tito** [comment] 2015-01-08 21:26
Duplicate of #109

**Closed** 2015-01-08 21:27 UTC
