### ISSUE TITLE
Recipe for the cryptography module

### ISSUE THREAD

**Issue by BitCode-in** [kivy/kivy-ios#786] opened 2023-03-28 16:55 UTC
**Good afternoon! Please add a recipe for the cryptography module.**
`Traceback (most recent call last):
   File "<string>", line 44, in load_module
   File "/Users/bitcode/Projects/ios/test/dist/root/python3/lib/python3.9/imp.py", line 342, in load_dynamic
   File "<frozen importlib._bootstrap>", line 711, in _load
   File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
   File "<frozen importlib._bootstrap>", line 565, in module_from_spec
   File "<frozen importlib._bootstrap_external>", line 1173, in create_module
   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
 ImportError: dynamic module does not define module export function (PyInit_cryptography_hazmat_bindings__rust)
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "/Users/bitcode/Projects/ios/test/test-ios/YourApp/main.py", line 5, in <module>
   File "/private/var/containers/Bundle/Application/test.app/lib/python3.9/site-packages/cryptography/fernet.py", line 14, in <module>
     from cryptography.hazmat.primitives import hashes, padding
   File "/private/var/containers/Bundle/Application/test.app/lib/python3.9/site-packages/cryptography/hazmat/primitives/padding.py", line 11, in <module>
     from cryptography.hazmat.bindings._rust import (
   File "<string>", line 48, in load_module
   File "/Users/bitcode/Projects/ios/test/dist/root/python3/lib/python3.9/imp.py", line 342, in load_dynamic
 ImportError: dynamic module does not define module export function (PyInit__rust)`

**Comment by misl6** [comment] 2023-03-29 17:37
Duplicate of #733

**Closed by misl6** 2023-03-29 17:37 UTC
Labels: feature request
