### ISSUE TITLE
 Unable to find any valuable Window provider with Kivy 1.10.0

### ISSUE THREAD

**Issue by Zen-CODE** [kivy/kivy-ios#251] opened 2017-05-15 05:44 UTC
When trying to run the app using the latest version (OSX 10.10.5), the app crashes as kivy.core.window.Window is None. 
```
2017-05-15 07:36:43.721 cami-apps[31169:223848] Available orientation: KIVY_ORIENTATION=LandscapeLeft LandscapeRight
2017-05-15 07:36:43.722 cami-apps[31169:223848] PythonHome is: /Users/camy/Library/Developer/CoreSimulator/Devices/3009F6DE-90EF-47C7-AA82-2B5142402125/data/Containers/Bundle/Application/79351255-9CD4-4740-93B2-AE825F04BE86/cami-apps.app
2017-05-15 07:36:43.725 cami-apps[31169:223848] Initializing python
2017-05-15 07:36:44.601 cami-apps[31169:223848] Running main.pyo: /Users/camy/Library/Developer/CoreSimulator/Devices/3009F6DE-90EF-47C7-AA82-2B5142402125/data/Containers/Bundle/Application/79351255-9CD4-4740-93B2-AE825F04BE86/cami-apps.app/YourApp/main.pyo
[INFO   ] [Kivy        ] v1.10.0
[INFO   ] [Python      ] v2.7.1 (r271:86832, May 14 2017, 22:09:45) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_imageio, img_tex (img_dds, img_sdl2, img_ffpyplayer, img_pil, img_gif ignored)
[INFO   ] [OSC         ] using <thread> for socket
[INFO   ] [Window      ] Provider: sdl2
[CRITICAL] [Window      ] Unable to find any valuable Window provider.
sdl2 - KeyError: 'kivy.graphics.cgl_backend.cgl_glew'
  File "/Users/camy/Repos/kivy-ios/build/kivy/i386/kivy-1.10.0/iosbuild/lib/python2.7/site-packages/kivy/core/__init__.py", line 67, in core_select_lib
  File "/Users/camy/Repos/kivy-ios/build/kivy/i386/kivy-1.10.0/iosbuild/lib/python2.7/site-packages/kivy/core/window/window_sdl2.py", line 140, in __init__
  File "/Users/camy/Repos/kivy-ios/build/kivy/i386/kivy-1.10.0/iosbuild/lib/python2.7/site-packages/kivy/core/window/__init__.py", line 899, in __init__
  File "/Users/camy/Repos/kivy-ios/build/kivy/i386/kivy-1.10.0/iosbuild/lib/python2.7/site-packages/kivy/core/window/window_sdl2.py", line 269, in create_window
  File "kivy/core/window/_window_sdl2.pyx", line 110, in kivy.core.window._window_sdl2._WindowSDL2Storage.setup_window (kivy/core/window/_window_sdl2.c:2036)
  File "kivy/graphics/cgl.pyx", line 52, in kivy.graphics.cgl.cgl_get_backend_name (kivy/graphics/cgl.c:2764)
  File "kivy/graphics/cgl.pyx", line 60, in kivy.graphics.cgl.cgl_get_backend_name (kivy/graphics/cgl.c:2616)
  File "/Users/camy/Repos/kivy-ios/dist/root/python/lib/python2.7/importlib/__init__.py", line 38, in import_module
```

**Comment by tito** [comment] 2017-05-19 11:49
Duplicate of #240 - as explained into the issue, regenate your project, or backport the change in main.m.

Once a project is generated, the main.m will never change (we don't know if you edited it or not)

**Closed by tito** 2017-05-19 11:49 UTC
