### ISSUE TITLE
Replacement for pycrypto

### ISSUE THREAD

**Issue by ahiemstra** [kivy/kivy-ios#843] opened 2023-08-20 11:34 UTC
**Is your feature request related to a problem? Please describe.**
I'm investigating if I can use KIVY / MIVYMD / KIVY-IOS to create platform independent apps with Python. I installed ivy-ios, and noticed that pycrypto v2.6 is included in the toolchain. However, this module is not being supported since Python 3.3.

**Describe the solution you'd like**
The replacement for pycrypto is pycryptodome. So that would be an obvious replacement. Or any other encryption module that is supported with Python 3.10+.

**Describe alternatives you've considered**
Alternatively I could create a recipe for pycryptodome myself, but I think I miss the knowledge to do so.

**Additional context**
I think including a depreciated module like pycrypto is not a good thing. So it might be time to replace it anyways.

Regards, Arjen.

**Comment by misl6** [comment] 2023-08-22 07:51
Hi @ahiemstra ,

Unless something changed recently on `pycryptodome` side, see: https://github.com/kivy/kivy-ios/issues/701#issuecomment-1167803582

(Everything is possible, but you'll likely required to do a lot of patching).

What I can suggest (and I do the same on my side), if speed is not an issue, is to implement the algorithm you need in plain-python.

**Comment by Julian-O** [comment] 2023-10-29 03:40
Closing as duplicate of #701

**Closed by Julian-O** 2023-10-29 03:40 UTC
Labels: awaiting-reply, feature request
